### ISSUE TITLE
[2024/07/13/토] 모델 성능 향상

### ISSUE THREAD

**Issue by zlwmxkdla** [Prize-Three/record#6]
### <저번주 진행 상황>
- 라마3 한국어 모델 이용해서 커스텀 데이터셋 파인튜닝하였고, 이 파인튜닝된 모델에 기존 라마 모델을 결합하여 허깅페이스에 0707의 이름으로 올려놓았었습니다. 
- 해당 모델 LM studio에서 사용하도록 gguf파일로도 변환하여 허깅 페이스의 0707_gguf 이름으로 올려놓았습니다. 

### 🔶 모델 성능 향상 시도
미영언니가 LM studio에서 작동시킨 영상 보고 모델 성능 높이고자 일단은 코랩에서 작동 진행했습니다. 

근데 문제가 허깅페이스에 업로드했던 해당 모델 가져와서 출력해보는 과정 했는데 답변이 엉망이었습니다.
<img width="900" height="250" alt="1" src="https://github.com/user-attachments/assets/903d9a31-5b44-471f-bced-598803553928">

### 🔶 해결책 - 프롬프트 엔지니어링
기존에 프롬프트의 역할에 대한 이해가 잘못되었던 것 같습니다. 그냥 입력하는 내용이 프롬프트라고 생각했는데
모델에게 전달할 입력은 key 혹은 instructions에 해당하고 프롬프트는 모델이 적절한 응답을 도출해내도록 방향성을 제시하는 문장이라고 할 수 있습니다.

미영언니가 올린 LM studio 서버 코드 보니까 해당 코드에는 프롬프트 엔지니어링이 수행되어 있었고 그렇기 때문에 코랩보다 성능이 높게 나왔습니다. 

`key = "어디가 아파서 왔어요?"
prompt = f"""you are an assistant please answer in korean language.`

이런 식으로 모델한테 역할을 부여하는게 프롬프트 엔지니어링에 해당합니다. 

<br>

<img width="900" height="250" alt="2" src="https://github.com/user-attachments/assets/b89f3027-59e1-407c-87fb-a6a289ed85ef">

그래서 병원놀이다 보니까 다음과 같이 ai의 역할을 명시해주었더니 답변은 잘 나오는데 문제는 이거 랜덤입니다..
답변 잘 나왔다 안나왔다 합니다...

### 🔶 미영언니 올렸던 colab에서 수행하는 ram 부족 관한 코멘트
허깅페이스에서 가져오는 거는 기존에 파인튜닝할 때 수행했던 양자화 기법으로 ram 부족 문제는 해결 가능합니다.

양자화 기법이란, 라마 모델이 방대하기 때문에 파인튜닝을 진행할 때 모든 파라미터를 건드리는 게 아니라 일부는 고정시키고 특정 파라미터만 변경하여 파인튜닝을 진행했습니다. 즉, 방대한 모델의 효율적인 파인튜닝을 위한 방식이 '양자화 기법'입니다. 

양자화 기법을 모델을 불러올 때도 적용할 수 있는데 이 기법 적용하면 메모리 사용량을 줄이고 모델의 추론을 효율적으로 수행할 수 있습니다. 

일단, 저만 colab 유료 버전을 사용하는 상황이라
양자화 기법을 사용하여 transformer 사용해서 모델 불러올 경우 양자화 기법을 사용하지 않았을 때보다 실행 시간은 짧습니다. 

### 🤔 답변이 너무 길게 출력되요...
커스텀 데이터셋의 문장의 끝에 endpoints를 설정해서 토큰화를 수행한 후에 모델 파인튜닝을 진행했습니다.
그래서, 해당 모델로 테스트했을 때는 정확하게 원하는 문장 하나만 출력합니다.

근데 이제 이 파인튜닝한 모델을 기존 모델과 결합해서 잘 작동하는지 확인했더니
![3](https://github.com/user-attachments/assets/ad4141c2-1226-4009-94e8-f663d19c8850)
위와 같이 너무 많은 답변이 출력됩니다..

이게 커스텀 데이터에는 endpoint가 적용된 상태로 학습이 진행되었는데 기존의 모델 자체에 endpoint가 없어서 그런건지 해결 못했습니다. 

아 그리고 여기서, 프롬프트 엔지니어링 적용했습니다.
그랬더니 다음과 같이 되게 성능은 높아졌어요
![4](https://github.com/user-attachments/assets/40cbd292-e2c8-475b-8d9b-d75a6abdf7f9)

기존에는 모델에 전달할 역할을 "you are a assistant please answer in korean lanauage"로만 했는데 
"You are an assistant, and your task is to answer in Korean as if you are a patient visiting a doctor. The doctor is asking questions to understand your symptoms better. Answer the doctor's questions in a detailed and respectful manner in Korean."로 바꿔서 역할을 자세하게 전달했더니 확실히 성능은 높아집니다.

....근데 왜 이렇게 많이 출력되는건지..이게 LM studio 서버 코드에 적용했을 때 해결되는지는 의문입니다. 

### 🔶 추가 데이터셋 학습
기존에 약 100개의 문장으로 파인튜닝된 모델에 추가로 새로운 데이터셋을 학습하는 것 시도해보려 했는데 기존 한국어 학습이 충분히 이루어져야 가능하다고 해서, 그리고 데이터셋을 구축하지 않아서 진행하지는 않았습니다. 이후에 성능 보완하기 위해 필요하다면 진행해야 할 것 같습니다. 추가 데이터셋으로 파인튜닝하는 과정 방법은 동일합니다.

## 결론
기존 LM studio 서버 코드의 프롬프트 엔지니어링 수행하면 성능 높아질 것 같습니다.
You are an assistant, and your task is to answer in Korean as if you are a patient visiting a doctor. The doctor is asking questions to understand your symptoms better. Answer the doctor's questions in a detailed and respectful manner in Korean. 이런 식으로 입력하면 될 것 같아요
대신 이렇게 할 경우 역할놀이 상황에 따라, 역할놀이에서의 ai의 역할에 따라 프롬프트 엔지니어링 각각 수행해야 할 것 같습니다..

**Comment by zlwmxkdla** [comment]
사진...클릭해서 봐주세요..클릭하면 잘 보여욤

**Comment by zlwmxkdla** [comment]
마크다운과 친하지 않아 가독성 떨어지는 점 죄송함다 시간 나면 깔끔하게 정리하겠슴다

**Comment by SeoMiYoung** [comment]
아하 프롬프트 엔지니어링이 LM Studio에 적용된지 몰랐었는데, 한번 제대로 적용해서 수행해봐야겠군요.
